print("Isi data identitas di bawah ini!")
print("=================================")
print(" ")
nama = str(input("Nama : "))
umur = int(input("Umur : "))
tinggi = float(input("Tinggi badan (cm) : "))
print(" ")
print("Nama saya {}, umur saya {} tahun dan tinggi saya {} cm.".format(nama, umur, tinggi))
print(" ")
print("=================================")